#!/bin/bash

rm -rf target/package
mkdir target/package
cp src/test/resources/clisson-server.properties target/package/
cp target/clisson-server-*-one-jar.jar target/package/clisson-server.jar
cp src/main/script/* target/package
